### ISSUE TITLE
Cron for the upnp request

### ISSUE THREAD

**Issue by gorucci** [XanderXAJ/docker-miniupnpc#8]
Hi. Thank you for your image. I do believe it's the best (or at least one of the best) upnpc image on dockerhub 💪.
Unfortunately, my router doesn't preserve upnp "leases" (if I can call it that) after reboot. Even though routers are not usually rebooted, I find this very limiting.
Can you please add some kind of cron integration to the image so it can send an upnp request every N seconds?

**Comment by XanderXAJ** [comment]
Thanks, it's a great suggestion. Apologies for the delay in getting back to you.

I've had a similar idea since creating this image to make a daemon version of it that could be run e.g. as part of a Docker Compose stack. It would make an open request when it starts (perhaps with a configurable re-request like you've suggested), and it would close the port when it stops.

As you can imagine since it hasn't happened yet, I haven't been able to make the time, but it would still be a cool project to do at some point, so never say never. 🙂 

In the meantime, since the image is simply repackaging the tool, you could potentially add it to your system's crontab (I'm assuming you have one)? For security you might want to put it in the `root` user's crontab:

```shell
sudo crontab -e
```

Then add a rule like:

```cron
# Every 5 minutes: Forward internal TCP port 1234 to external port 12345
*/5 * * * * docker run --rm --net=host xanderxaj/miniupnpc -r 1234 12345 TCP
```

**Comment by gorucci** [comment]
Well, alternating the host settings is kinda negates docker's purpose for me (I use it for encapsulation of deployed services). Anyway, I ended up with such a solution:
```yaml
services:

  ## UPnP IGD -- url of my router leases
  ## Alternate path -- https://maxtroughear.dev/docs/infrastructure/docker-upnp/
  ## https://github.com/XanderXAJ/docker-miniupnpc
  upnp:
    image: xanderxaj/miniupnpc:latest ## https://registry.hub.docker.com/layers/xanderxaj/miniupnpc/latest/images/sha256-ce78681a59f79e17df6bdf740291bbabd42aa7d52f4c5652fe5ad7435cab50f2?context=explore 
    restart: unless-stopped
    network_mode: "host"
    environment:
      - FORWARDING_NAME=my_name
      - PORT=22222
      - EXTERNAL_PORT=22222
    entrypoint: ## https://manpages.debian.org/unstable/miniupnpc/upnpc.1.en.html
      - sh
      - "-c"
      - >
        upnpc -e "$$FORWARDING_NAME" -a @ $$PORT $$EXTERNAL_PORT TCP 300
        && sleep 3m ## todo switch to plain cron
```

It restarts the container with upnpc every 3 minutes. Container itself requests 5 minute lease. It is not very elegant, but it works for me.
